# ═══════════════════════════════════════════════════════════
#  LIBRARY AI PRO  ·  Complete Dataset (Train System Removed)
# ═══════════════════════════════════════════════════════════

BOOKS_DATA = [
    # ── FICTION ──────────────────────────────────────────────
    {"title":"The Great Gatsby","author":"F. Scott Fitzgerald","genre":"Fiction","year":1925,"pages":180,"rating":4.2,"borrows":210,"color":"#6366f1","isbn":"978-0743273565","publisher":"Scribner","award":"Modern Library Top 100","ebook":True,"audio":True,"price":12.99,"desc":"The story of Jay Gatsby's obsessive love for Daisy Buchanan, set against the glittering Jazz Age. A devastating critique of the American Dream and the hollowness of wealth."},
    {"title":"To Kill a Mockingbird","author":"Harper Lee","genre":"Fiction","year":1960,"pages":281,"rating":4.8,"borrows":340,"color":"#a78bfa","isbn":"978-0061935466","publisher":"J.B. Lippincott","award":"Pulitzer Prize 1961","ebook":True,"audio":True,"price":14.99,"desc":"A powerful story of racial injustice in the American South, told through young Scout Finch as her father defends a Black man falsely accused of a crime. A masterpiece of moral courage."},
    {"title":"1984","author":"George Orwell","genre":"Fiction","year":1949,"pages":328,"rating":4.7,"borrows":290,"color":"#ef4444","isbn":"978-0451524935","publisher":"Secker & Warburg","award":"Prometheus Award","ebook":True,"audio":True,"price":11.99,"desc":"A chilling dystopian vision where Big Brother watches everything, truth is manufactured, and independent thought is a crime. One of the most influential novels ever written."},
    {"title":"Brave New World","author":"Aldous Huxley","genre":"Fiction","year":1932,"pages":311,"rating":4.2,"borrows":195,"color":"#10b981","isbn":"978-0060850524","publisher":"Chatto & Windus","award":"Hugo Award","ebook":True,"audio":True,"price":11.99,"desc":"A dystopian world where humans are genetically engineered and conditioned for happiness — but at the cost of art, family, and freedom. A visionary masterwork."},
    {"title":"The Alchemist","author":"Paulo Coelho","genre":"Fiction","year":1988,"pages":208,"rating":4.6,"borrows":380,"color":"#f97316","isbn":"978-0062315007","publisher":"HarperOne","award":"Bestseller 65M+ copies","ebook":True,"audio":True,"price":13.99,"desc":"A shepherd boy's journey across the Sahara to follow his Personal Legend. The global phenomenon translated into 80 languages, inspiring millions to pursue their dreams."},
    {"title":"The Catcher in the Rye","author":"J.D. Salinger","genre":"Fiction","year":1951,"pages":277,"rating":4.0,"borrows":180,"color":"#f59e0b","isbn":"978-0316769174","publisher":"Little, Brown","award":"Modern Library Top 100","ebook":False,"audio":True,"price":12.99,"desc":"Holden Caulfield's journey through New York City after being expelled from school — a timeless story of teenage alienation and the pain of growing up."},
    {"title":"The Book Thief","author":"Markus Zusak","genre":"Fiction","year":2005,"pages":552,"rating":4.8,"borrows":270,"color":"#4c1d95","isbn":"978-0375842207","publisher":"Picador","award":"Printz Honor Award","ebook":True,"audio":True,"price":15.99,"desc":"Narrated by Death himself, this is the story of Liesel in Nazi Germany who steals books and shares them with others. A stunning meditation on the power of words."},
    {"title":"One Hundred Years of Solitude","author":"Gabriel García Márquez","genre":"Fiction","year":1967,"pages":417,"rating":4.6,"borrows":225,"color":"#166534","isbn":"978-0060883287","publisher":"Harper & Row","award":"Nobel Prize in Literature","ebook":True,"audio":True,"price":14.99,"desc":"The Buendía family's multi-generational story in the fictional town of Macondo. The masterpiece of magical realism and one of the greatest novels in any language."},
    {"title":"Crime and Punishment","author":"Fyodor Dostoevsky","genre":"Fiction","year":1866,"pages":671,"rating":4.6,"borrows":185,"color":"#1e1b4b","isbn":"978-0140449136","publisher":"The Russian Messenger","award":"World Classic","ebook":True,"audio":True,"price":10.99,"desc":"A student commits murder believing himself above conventional morality, then struggles with overwhelming guilt and psychological torment. A cornerstone of world literature."},
    {"title":"The Kite Runner","author":"Khaled Hosseini","genre":"Fiction","year":2003,"pages":372,"rating":4.7,"borrows":310,"color":"#7e22ce","isbn":"978-1594631931","publisher":"Riverhead Books","award":"Book Sense Award","ebook":True,"audio":True,"price":14.99,"desc":"A sweeping story of friendship and betrayal set against the backdrop of Afghanistan from the final days of the monarchy through the Taliban regime. Breathtakingly powerful."},

    # ── FANTASY ──────────────────────────────────────────────
    {"title":"Harry Potter and the Sorcerer's Stone","author":"J.K. Rowling","genre":"Fantasy","year":1997,"pages":309,"rating":4.9,"borrows":450,"color":"#8b5cf6","isbn":"978-0439708180","publisher":"Bloomsbury","award":"British Book Award","ebook":True,"audio":True,"price":16.99,"desc":"An orphaned boy discovers he is a wizard on his 11th birthday and enters Hogwarts. The book that ignited one of the greatest literary phenomena of all time — over 500M copies sold."},
    {"title":"The Lord of the Rings","author":"J.R.R. Tolkien","genre":"Fantasy","year":1954,"pages":1178,"rating":4.8,"borrows":320,"color":"#059669","isbn":"978-0618640157","publisher":"Allen & Unwin","award":"International Fantasy Award","ebook":True,"audio":True,"price":22.99,"desc":"The epic quest to destroy the One Ring and defeat the Dark Lord Sauron. The foundation of modern fantasy with unparalleled world-building and storytelling across three volumes."},
    {"title":"The Hobbit","author":"J.R.R. Tolkien","genre":"Fantasy","year":1937,"pages":310,"rating":4.7,"borrows":285,"color":"#16a34a","isbn":"978-0547928227","publisher":"Allen & Unwin","award":"Lewis Carroll Shelf Award","ebook":True,"audio":True,"price":14.99,"desc":"Bilbo Baggins is swept into an epic quest with thirteen dwarves to reclaim the Lonely Mountain's treasure from the dragon Smaug. The prequel to an unforgettable trilogy."},
    {"title":"The Name of the Wind","author":"Patrick Rothfuss","genre":"Fantasy","year":2007,"pages":662,"rating":4.6,"borrows":195,"color":"#065f46","isbn":"978-0756404079","publisher":"DAW Books","award":"Quill Award","ebook":True,"audio":True,"price":15.99,"desc":"Kvothe, the most notorious wizard of his age, recounts his extraordinary life from childhood in a traveling troupe to his time at the University. Lyrical and gripping."},
    {"title":"The Hunger Games","author":"Suzanne Collins","genre":"Fantasy","year":2008,"pages":374,"rating":4.6,"borrows":360,"color":"#78350f","isbn":"978-0439023481","publisher":"Scholastic","award":"NYT Bestseller","ebook":True,"audio":True,"price":13.99,"desc":"In a dystopian future, 16-year-old Katniss Everdeen volunteers to fight in a televised battle to the death. A gripping story of courage, survival, and resistance against oppression."},

    # ── SCIENCE ──────────────────────────────────────────────
    {"title":"A Brief History of Time","author":"Stephen Hawking","genre":"Science","year":1988,"pages":212,"rating":4.8,"borrows":310,"color":"#1d4ed8","isbn":"978-0553380163","publisher":"Bantam Books","award":"Royal Society Prize","ebook":True,"audio":True,"price":13.99,"desc":"From the Big Bang to black holes, Hawking takes readers on a journey through space and time. The most successful popular science book ever — 10M+ copies sold worldwide."},
    {"title":"Dune","author":"Frank Herbert","genre":"Science","year":1965,"pages":688,"rating":4.7,"borrows":260,"color":"#b45309","isbn":"978-0441013593","publisher":"Chilton Books","award":"Hugo & Nebula Awards","ebook":True,"audio":True,"price":15.99,"desc":"On the desert planet Arrakis, young Paul Atreides navigates politics, religion, and ecology in a universe where control of 'spice' means control of the universe. Best-selling sci-fi ever."},
    {"title":"The Hitchhiker's Guide to the Galaxy","author":"Douglas Adams","genre":"Science","year":1979,"pages":224,"rating":4.6,"borrows":220,"color":"#0891b2","isbn":"978-0345391803","publisher":"Pan Books","award":"BSFA Award","ebook":True,"audio":True,"price":12.99,"desc":"Moments before Earth is demolished, Arthur Dent is whisked through the galaxy. Brilliantly funny, philosophically profound, and utterly unlike anything else ever written."},
    {"title":"The Selfish Gene","author":"Richard Dawkins","genre":"Science","year":1976,"pages":360,"rating":4.5,"borrows":195,"color":"#065f46","isbn":"978-0198788607","publisher":"Oxford University Press","award":"Royal Society Award","ebook":True,"audio":True,"price":13.99,"desc":"Dawkins presents a gene-centered view of evolution and coins the term 'meme.' A revolutionary book that changed how we understand natural selection, altruism, and human behavior."},
    {"title":"Cosmos","author":"Carl Sagan","genre":"Science","year":1980,"pages":365,"rating":4.8,"borrows":260,"color":"#1e3a5f","isbn":"978-0345539434","publisher":"Random House","award":"Hugo Award","ebook":True,"audio":True,"price":14.99,"desc":"Carl Sagan's magnificent journey through the universe — its origin, evolution, and humanity's place within it. One of the most beloved popular science books ever written."},
    {"title":"Sapiens","author":"Yuval Noah Harari","genre":"Science","year":2011,"pages":443,"rating":4.7,"borrows":400,"color":"#0284c7","isbn":"978-0062316097","publisher":"Harper","award":"Bestseller 15M+ copies","ebook":True,"audio":True,"price":16.99,"desc":"A sweeping history of humankind from the Stone Age through the 21st century. Harari examines how biology and history shaped our species — and where we are heading."},
    {"title":"Homo Deus","author":"Yuval Noah Harari","genre":"Science","year":2015,"pages":450,"rating":4.5,"borrows":230,"color":"#0369a1","isbn":"978-0062464316","publisher":"Harvill Secker","award":"International Bestseller","ebook":True,"audio":True,"price":15.99,"desc":"Harari explores humanity's future — AI, genetic engineering, the quest for immortality — and asks what happens to democracy when algorithms know us better than we know ourselves."},

    # ── HISTORY ──────────────────────────────────────────────
    {"title":"Guns, Germs, and Steel","author":"Jared Diamond","genre":"History","year":1997,"pages":498,"rating":4.3,"borrows":210,"color":"#4d7c0f","isbn":"978-0393317558","publisher":"W.W. Norton","award":"Pulitzer Prize","ebook":True,"audio":True,"price":15.99,"desc":"Why did Western civilization dominate others? Diamond's groundbreaking answer overturns racist theories and shows how geography and biology shaped all of human history."},
    {"title":"The Diary of a Young Girl","author":"Anne Frank","genre":"History","year":1947,"pages":283,"rating":4.7,"borrows":255,"color":"#dc2626","isbn":"978-0553296983","publisher":"Contact Publishing","award":"UNESCO Memory of World","ebook":True,"audio":True,"price":11.99,"desc":"Anne Frank's diary, written while hiding from the Nazis 1942–1944. One of the most important documents of the 20th century — translated into 70+ languages."},

    # ── BIOGRAPHY ────────────────────────────────────────────
    {"title":"Steve Jobs","author":"Walter Isaacson","genre":"Biography","year":2011,"pages":571,"rating":4.6,"borrows":295,"color":"#374151","isbn":"978-1451648539","publisher":"Simon & Schuster","award":"Bestseller","ebook":True,"audio":True,"price":18.99,"desc":"The exclusive biography of Apple's co-founder, based on 40+ interviews. A riveting story of creativity, obsession, and the drive to 'put a dent in the universe.'"},
    {"title":"Becoming","author":"Michelle Obama","genre":"Biography","year":2018,"pages":448,"rating":4.8,"borrows":380,"color":"#7c3aed","isbn":"978-1524763138","publisher":"Crown","award":"Grammy Award Audiobook","ebook":True,"audio":True,"price":17.99,"desc":"The intimate memoir of the former First Lady — from childhood in Chicago to the White House. One of the best-selling memoirs in history with 14M+ copies sold."},
    {"title":"Long Walk to Freedom","author":"Nelson Mandela","genre":"Biography","year":1994,"pages":656,"rating":4.9,"borrows":270,"color":"#059669","isbn":"978-0316548182","publisher":"Little, Brown","award":"Nobel Peace Prize Winner","ebook":True,"audio":True,"price":16.99,"desc":"Nelson Mandela's autobiography from rural childhood to 27 years in prison to inauguration as South Africa's first democratically elected president. Profoundly inspiring."},
    {"title":"Elon Musk","author":"Walter Isaacson","genre":"Biography","year":2023,"pages":688,"rating":4.5,"borrows":310,"color":"#0f172a","isbn":"978-1982181284","publisher":"Simon & Schuster","award":"#1 Bestseller 2023","ebook":True,"audio":True,"price":19.99,"desc":"The definitive biography — from his traumatic childhood in South Africa to building Tesla, SpaceX, and acquiring Twitter. Unflinchingly honest and endlessly fascinating."},
    {"title":"Educated","author":"Tara Westover","genre":"Biography","year":2018,"pages":352,"rating":4.8,"borrows":285,"color":"#dc2626","isbn":"978-0399590504","publisher":"Random House","award":"Goodreads Best Memoir","ebook":True,"audio":True,"price":15.99,"desc":"A young woman grows up in a survivalist family, never attending school, yet earns a PhD from Cambridge. A story of self-invention and the transformative power of education."},

    # ── TECHNOLOGY ───────────────────────────────────────────
    {"title":"Clean Code","author":"Robert C. Martin","genre":"Technology","year":2008,"pages":431,"rating":4.6,"borrows":320,"color":"#1e40af","isbn":"978-0132350884","publisher":"Prentice Hall","award":"Tech Classic","ebook":True,"audio":False,"price":34.99,"desc":"The bible of software craftsmanship. Uncle Bob's principles for writing readable, maintainable, and elegant code. Required reading for every serious software developer."},
    {"title":"The Pragmatic Programmer","author":"David Thomas & Andrew Hunt","genre":"Technology","year":1999,"pages":352,"rating":4.7,"borrows":280,"color":"#1e3a5f","isbn":"978-0135957059","publisher":"Addison-Wesley","award":"Jolt Award","ebook":True,"audio":False,"price":32.99,"desc":"From journeyman to master — comprehensive advice on every aspect of software development with practical exercises and anecdotes that make complex topics memorable."},
    {"title":"Zero to One","author":"Peter Thiel","genre":"Technology","year":2014,"pages":224,"rating":4.5,"borrows":265,"color":"#0c4a6e","isbn":"978-0804139021","publisher":"Crown Business","award":"WSJ Bestseller","ebook":True,"audio":True,"price":14.99,"desc":"Thiel's contrarian thinking on startups — why the next breakthrough will not be an imitation of what exists, and what it truly takes to build a transformative company."},
    {"title":"Deep Work","author":"Cal Newport","genre":"Technology","year":2016,"pages":296,"rating":4.6,"borrows":245,"color":"#1e293b","isbn":"978-1455586691","publisher":"Grand Central","award":"WSJ Bestseller","ebook":True,"audio":True,"price":14.99,"desc":"Rules for focused success in a distracted world. Newport argues that the ability to focus without distraction is becoming increasingly rare and increasingly valuable."},
    {"title":"AI: A Modern Approach","author":"Stuart Russell & Peter Norvig","genre":"Technology","year":1994,"pages":1132,"rating":4.7,"borrows":230,"color":"#312e81","isbn":"978-0136042594","publisher":"Pearson","award":"ACM Award","ebook":True,"audio":False,"price":89.99,"desc":"The standard AI textbook used in 1500+ universities worldwide. Comprehensive coverage of machine learning, NLP, robotics, and computer vision — the definitive reference."},

    # ── SELF-HELP ────────────────────────────────────────────
    {"title":"Atomic Habits","author":"James Clear","genre":"Self-Help","year":2018,"pages":320,"rating":4.8,"borrows":480,"color":"#7c3aed","isbn":"978-0735211292","publisher":"Avery","award":"#1 NYT Bestseller","ebook":True,"audio":True,"price":16.99,"desc":"A revolutionary system for building good habits. Clear explains how tiny 1% improvements compound into life-changing results. The most practical habit book ever written."},
    {"title":"Think and Grow Rich","author":"Napoleon Hill","genre":"Self-Help","year":1937,"pages":320,"rating":4.4,"borrows":265,"color":"#d97706","isbn":"978-1585424337","publisher":"The Ralston Society","award":"Bestseller 100M+ copies","ebook":True,"audio":True,"price":10.99,"desc":"Based on interviews with 500+ millionaires, Hill distills the principles of success into 13 concrete steps. One of the best-selling books of all time."},
    {"title":"The 7 Habits of Highly Effective People","author":"Stephen R. Covey","genre":"Self-Help","year":1989,"pages":372,"rating":4.5,"borrows":290,"color":"#c2410c","isbn":"978-0743269513","publisher":"Free Press","award":"Bestseller 40M+ copies","ebook":True,"audio":True,"price":15.99,"desc":"A principle-centered approach for solving personal and professional problems. Covey's framework has changed millions of lives and transformed countless organizations worldwide."},
    {"title":"Ikigai","author":"Héctor García","genre":"Self-Help","year":2016,"pages":194,"rating":4.4,"borrows":235,"color":"#db2777","isbn":"978-0143130727","publisher":"Penguin","award":"International Bestseller","ebook":True,"audio":True,"price":12.99,"desc":"Explores the Japanese concept of ikigai — your reason for being — and reveals the secrets behind the world's longest-living people in Okinawa. A beautiful philosophy for a meaningful life."},
    {"title":"The Power of Now","author":"Eckhart Tolle","genre":"Self-Help","year":1997,"pages":236,"rating":4.5,"borrows":220,"color":"#065f46","isbn":"978-1577314806","publisher":"New World Library","award":"Oprah Book Club","ebook":True,"audio":True,"price":13.99,"desc":"A guide to spiritual enlightenment through present-moment awareness. Tolle's transformative message has made this one of the most significant spiritual books of our era."},
    {"title":"Rich Dad Poor Dad","author":"Robert T. Kiyosaki","genre":"Self-Help","year":1997,"pages":336,"rating":4.3,"borrows":350,"color":"#92400e","isbn":"978-1612680194","publisher":"Warner Books","award":"Bestseller 32M+ copies","ebook":True,"audio":True,"price":13.99,"desc":"What the rich teach their kids about money that the poor and middle class do not. Challenges conventional wisdom about wealth, work, and financial independence."},

    # ── PHILOSOPHY ───────────────────────────────────────────
    {"title":"Meditations","author":"Marcus Aurelius","genre":"Philosophy","year":180,"pages":253,"rating":4.8,"borrows":285,"color":"#92400e","isbn":"978-0812968255","publisher":"Modern Library","award":"Timeless Classic","ebook":True,"audio":True,"price":9.99,"desc":"The private reflections of the Roman Emperor on Stoic philosophy — written as a personal diary never meant for publication. Among history's greatest works of moral philosophy."},
    {"title":"Man's Search for Meaning","author":"Viktor Frankl","genre":"Philosophy","year":1946,"pages":200,"rating":4.9,"borrows":310,"color":"#164e63","isbn":"978-0807014295","publisher":"Beacon Press","award":"One of 10 Most Influential Books","ebook":True,"audio":True,"price":11.99,"desc":"Psychiatrist Viktor Frankl's harrowing account of survival in Nazi concentration camps and his discovery that finding meaning in suffering is the key to human survival."},
    {"title":"The Art of War","author":"Sun Tzu","genre":"Philosophy","year":-500,"pages":273,"rating":4.5,"borrows":245,"color":"#7f1d1d","isbn":"978-1599869773","publisher":"Filiquarian","award":"Timeless Classic","ebook":True,"audio":True,"price":8.99,"desc":"Ancient Chinese military treatise that has shaped strategy, business, and leadership for 2,500 years. Still relevant for anyone who must compete and win with limited resources."},
    {"title":"The Republic","author":"Plato","genre":"Philosophy","year":-380,"pages":416,"rating":4.4,"borrows":180,"color":"#b45309","isbn":"978-0872201361","publisher":"Hackett","award":"Foundation of Philosophy","ebook":True,"audio":True,"price":9.99,"desc":"Plato's exploration of justice, beauty, and the ideal state through the character of Socrates. The foundational text of Western political philosophy."},

    # ── MYSTERY ──────────────────────────────────────────────
    {"title":"Gone Girl","author":"Gillian Flynn","genre":"Mystery","year":2012,"pages":422,"rating":4.2,"borrows":275,"color":"#1e1b4b","isbn":"978-0307588371","publisher":"Crown","award":"Goodreads Choice Award","ebook":True,"audio":True,"price":13.99,"desc":"On their fifth anniversary, Nick Dunne's wife Amy disappears. This razor-sharp psychological thriller about marriage, media, and perfectly constructed deceptions is endlessly gripping."},
    {"title":"The Girl with the Dragon Tattoo","author":"Stieg Larsson","genre":"Mystery","year":2005,"pages":672,"rating":4.3,"borrows":290,"color":"#1f2937","isbn":"978-0307454546","publisher":"Norstedts","award":"Bestseller 80M+ copies","ebook":True,"audio":True,"price":14.99,"desc":"Journalist Mikael Blomkvist and hacker Lisbeth Salander investigate a decades-old disappearance. A gripping, atmospheric thriller that became a global sensation."},
    {"title":"And Then There Were None","author":"Agatha Christie","genre":"Mystery","year":1939,"pages":264,"rating":4.6,"borrows":235,"color":"#312e81","isbn":"978-0062073488","publisher":"Collins Crime Club","award":"Best Crime Novel Ever Written","ebook":True,"audio":True,"price":11.99,"desc":"Ten strangers on an isolated island are murdered one by one. Christie's masterpiece is the best-selling crime novel of all time with 100M+ copies sold."},
    {"title":"The Da Vinci Code","author":"Dan Brown","genre":"Mystery","year":2003,"pages":454,"rating":4.0,"borrows":320,"color":"#1c1917","isbn":"978-0307474278","publisher":"Doubleday","award":"Bestseller 80M+ copies","ebook":True,"audio":True,"price":13.99,"desc":"Harvard symbologist Robert Langdon investigates a murder in the Louvre and uncovers a conspiracy that could rock the foundations of Christianity. One of the best-selling novels of all time."},

    # ── CHILDREN ─────────────────────────────────────────────
    {"title":"The Little Prince","author":"Antoine de Saint-Exupéry","genre":"Children","year":1943,"pages":96,"rating":4.8,"borrows":295,"color":"#0c4a6e","isbn":"978-0156012195","publisher":"Reynal & Hitchcock","award":"Bestseller 200M+ copies","ebook":True,"audio":True,"price":9.99,"desc":"A young prince travels from planet to planet, encountering the strangeness of adult life. The most read and translated French-language book in history — cherished by all ages."},
    {"title":"Charlotte's Web","author":"E.B. White","genre":"Children","year":1952,"pages":184,"rating":4.7,"borrows":245,"color":"#166534","isbn":"978-0061124952","publisher":"Harper & Brothers","award":"Newbery Honor","ebook":True,"audio":True,"price":10.99,"desc":"The gentle story of friendship between a pig named Wilbur and a spider named Charlotte, who saves his life with her words. A classic meditation on friendship and loss."},

    # ── ROMANCE ──────────────────────────────────────────────
    {"title":"Pride and Prejudice","author":"Jane Austen","genre":"Romance","year":1813,"pages":432,"rating":4.5,"borrows":270,"color":"#ec4899","isbn":"978-0141439518","publisher":"T. Egerton","award":"Classic Literature","ebook":True,"audio":True,"price":9.99,"desc":"The witty and romantic story of Elizabeth Bennet and Mr. Darcy, exploring love, class, and social expectations in Regency England. Austen's most beloved novel."},
    {"title":"The Notebook","author":"Nicholas Sparks","genre":"Romance","year":1996,"pages":214,"rating":4.3,"borrows":210,"color":"#f43f5e","isbn":"978-0446605236","publisher":"Warner Books","award":"International Bestseller","ebook":True,"audio":True,"price":12.99,"desc":"A timeless story of love between Noah and Allie, separated by class and circumstance but eternally bound by a summer romance. One of the most beloved love stories of our era."},

    # ── HEALTH ───────────────────────────────────────────────
    {"title":"Why We Sleep","author":"Matthew Walker","genre":"Health","year":2017,"pages":368,"rating":4.7,"borrows":260,"color":"#1e3a5f","isbn":"978-1501144325","publisher":"Scribner","award":"Goodreads Choice Award","ebook":True,"audio":True,"price":15.99,"desc":"Neuroscientist Walker reveals sleep's profound impact on health, memory, creativity, and longevity. This book will forever change how you think about rest and productivity."},
    {"title":"The Body","author":"Bill Bryson","genre":"Health","year":2019,"pages":464,"rating":4.7,"borrows":215,"color":"#0f766e","isbn":"978-0385539302","publisher":"Doubleday","award":"Goodreads Science Winner","ebook":True,"audio":True,"price":16.99,"desc":"Bryson takes us on a head-to-toe tour of the human body, explaining how it all works with his characteristic wit and wonder. Science writing at its most entertaining."},

    # ── ART ──────────────────────────────────────────────────
    {"title":"The Story of Art","author":"E.H. Gombrich","genre":"Art","year":1950,"pages":688,"rating":4.7,"borrows":160,"color":"#9f1239","isbn":"978-0714832470","publisher":"Phaidon Press","award":"Classic Art Text","ebook":True,"audio":False,"price":29.99,"desc":"The world's most famous and popular book on art — tracing the history of art from cave paintings to the 20th century. The book that makes art accessible to everyone."},

    # ── SPORTS ───────────────────────────────────────────────
    {"title":"Shoe Dog","author":"Phil Knight","genre":"Sports","year":2016,"pages":386,"rating":4.7,"borrows":195,"color":"#115e59","isbn":"978-1501135910","publisher":"Scribner","award":"Goodreads Choice Award","ebook":True,"audio":True,"price":15.99,"desc":"Phil Knight's memoir recounting the founding of Nike — from a handshake deal with a Japanese shoe manufacturer to building one of the world's most iconic brands."},
    {"title":"The Last Dance","author":"Michael Jordan","genre":"Sports","year":2020,"pages":320,"rating":4.5,"borrows":175,"color":"#1e1b4b","isbn":"978-1984822529","publisher":"Harmony Books","award":"Bestseller","ebook":True,"audio":True,"price":17.99,"desc":"The behind-the-scenes story of the Chicago Bulls' final championship season with Michael Jordan — the greatest basketball player of all time. Raw, honest, and unmissable."},
]

BOOK_SUMMARIES = {
    "The Great Gatsby": "Jay Gatsby throws lavish parties every weekend hoping to attract his lost love Daisy Buchanan. Through the narrator Nick Carraway, Fitzgerald crafts a devastating portrait of the American Dream's corruption — beautiful on the surface, hollow beneath. The green light at the end of Daisy's dock becomes the symbol of all unattainable dreams.",
    "To Kill a Mockingbird": "Lawyer Atticus Finch defends Tom Robinson, a Black man falsely accused of raping a white woman in 1930s Alabama. His daughter Scout narrates this story of innocence, prejudice, and moral courage. One of the most important American novels ever written, it became the conscience of a nation.",
    "1984": "In Airstrip One, Winston Smith works for the Ministry of Truth rewriting history to match the Party's current narrative. He secretly rebels against the all-knowing Big Brother — but the Party is always watching. Orwell's warning about totalitarianism, surveillance, and the manipulation of truth remains terrifyingly relevant.",
    "Atomic Habits": "James Clear argues that success is the product of daily habits, not transformations. Using the Four Laws of Behavior Change, he shows how to make good habits obvious, attractive, easy, and satisfying — and bad ones the opposite. A 1% improvement every day leads to being 37 times better in a year.",
    "Sapiens": "Harari covers 70,000 years of human history in four revolutions: Cognitive (language), Agricultural (farming), Unification (money, empire, religion), and Scientific. He challenges everything we think we know about what makes us human and what gave Homo sapiens dominion over the Earth.",
    "Harry Potter and the Sorcerer's Stone": "On his 11th birthday, Harry discovers he's a wizard and enters Hogwarts School. With Ron and Hermione, he uncovers the mystery of the Sorcerer's Stone and confronts Lord Voldemort for the first time. Rowling created a complete magical universe that captured the imagination of generations.",
    "A Brief History of Time": "Hawking explains black holes, the Big Bang, the nature of time, and the search for a unified theory of physics — without a single equation. He asks: Did God create the universe, or does science provide a complete explanation? A book that made physics accessible to millions.",
    "Man's Search for Meaning": "Frankl describes life in Auschwitz and other Nazi camps, observing that those who survived found meaning even in suffering. He developed logotherapy: the idea that finding purpose — not pleasure — is the primary human motivation. Short, but immeasurably profound.",
    "The Alchemist": "Santiago, an Andalusian shepherd, dreams of treasure near the Egyptian pyramids. His journey across North Africa teaches him that 'when you want something, all the universe conspires in helping you to achieve it.' A philosophical fable about following your Personal Legend.",
    "Becoming": "Michelle Obama takes readers from her childhood on Chicago's South Side through Princeton, Harvard Law, her career, marriage to Barack, and eight extraordinary years in the White House. Honest, inspiring, and deeply human — one of the best-selling memoirs in history.",
    "Meditations": "Written as personal notes to himself, Marcus Aurelius reflects on Stoic principles: live in accordance with nature, accept what you cannot change, focus only on what is within your control. Remarkable wisdom from the most powerful man on Earth — written with no intention of ever being published.",
    "Clean Code": "Martin teaches that code is read far more than it is written. Through hundreds of examples, he shows how to write functions that do one thing, choose meaningful names, write self-documenting code, and refactor relentlessly toward simplicity. Required reading for every software professional.",
    "Educated": "Tara Westover grew up in a fundamentalist survivalist family that rejected medicine, government, and schooling. She taught herself algebra to pass the ACT, won a place at BYU, then earned a PhD from Cambridge — without ever attending school as a child. A story of extraordinary will.",
    "Gone Girl": "Nick Dunne's wife Amy goes missing on their fifth anniversary. The twists keep coming in this razor-sharp thriller about marriage, media, and carefully constructed deceptions. Flynn's unreliable narrators make every page a revelation. Possibly the best psychological thriller ever written.",
    "Dune": "Paul Atreides's noble family is betrayed and destroyed on the desert planet Arrakis. The only source of 'spice' — the universe's most valuable substance — Arrakis becomes Paul's crucible as he transforms into Muad'Dib, a messianic figure. Science fiction at its most epic.",
    "Why We Sleep": "Walker reveals that sleep is the single most effective thing we can do to reset our brain and body health. Poor sleep is linked to cancer, Alzheimer's, obesity, depression, and heart disease. The book argues we are in the middle of a catastrophic global sleep loss epidemic.",
    "The Kite Runner": "Amir, a wealthy Pashtun boy from Kabul, and Hassan, his Hazara servant, share a bond forged in childhood — then shattered by a single act of cowardice. Decades later, Amir returns to Taliban-controlled Afghanistan seeking redemption. A devastating and beautiful story.",
    "Brave New World": "In a future London, humans are manufactured in hatcheries and conditioned from birth to occupy their predetermined role in society. John the Savage, brought from a Reservation, challenges this 'perfect' civilization. Huxley's prescient warning remains one of literature's greatest novels.",
}

LEARNING_PATHS = {
    "🎓 Software Engineer":  ["Clean Code","The Pragmatic Programmer","Deep Work","Zero to One","Atomic Habits"],
    "🧪 Data Scientist":     ["AI: A Modern Approach","A Brief History of Time","The Selfish Gene","Deep Work","Sapiens"],
    "🚀 Entrepreneur":       ["Zero to One","Steve Jobs","Rich Dad Poor Dad","Think and Grow Rich","The 7 Habits of Highly Effective People"],
    "📖 Philosopher":        ["Meditations","The Republic","Man's Search for Meaning","The Art of War","Homo Deus"],
    "🌍 Historian":          ["Sapiens","Guns, Germs, and Steel","Homo Deus","The Diary of a Young Girl","A Brief History of Time"],
    "✍️ Creative Writer":    ["The Great Gatsby","1984","The Book Thief","One Hundred Years of Solitude","The Kite Runner"],
    "🧘 Life Balance":       ["Ikigai","The Power of Now","Why We Sleep","Man's Search for Meaning","Atomic Habits"],
    "🕵️ Mystery Lover":     ["And Then There Were None","Gone Girl","The Girl with the Dragon Tattoo","The Da Vinci Code","Crime and Punishment"],
    "💡 Tech Leader":        ["Zero to One","Steve Jobs","Elon Musk","Deep Work","AI: A Modern Approach"],
    "🏋️ Wellness":          ["Why We Sleep","The Body","Atomic Habits","Ikigai","The Power of Now"],
}

DEMO_REVIEWS = {
    "Atomic Habits": [
        {"user":"Ahmed Mohammed","rating":5,"text":"Life-changing! The 1% better concept transformed how I approach every goal.","date":"2024-11-15"},
        {"user":"Sara Hassan","rating":5,"text":"Best self-help book I've ever read. Clear and actionable throughout.","date":"2024-10-28"},
        {"user":"James Wilson","rating":4,"text":"Excellent practical advice. The habit stacking technique is genius.","date":"2024-12-01"},
    ],
    "Harry Potter and the Sorcerer's Stone": [
        {"user":"Sara Hassan","rating":5,"text":"Re-read this for the 5th time and still absolutely love every page!","date":"2024-11-20"},
        {"user":"Ahmed Mohammed","rating":5,"text":"J.K. Rowling built an entire universe. A true masterpiece of imagination.","date":"2024-09-14"},
    ],
    "Sapiens": [
        {"user":"Dr. Admin","rating":5,"text":"Harari completely changed my perspective on human history. Mind-blowing.","date":"2024-10-05"},
        {"user":"James Wilson","rating":4,"text":"Provocative and insightful. Some claims are bold but the narrative is gripping.","date":"2024-11-30"},
    ],
    "Man's Search for Meaning": [
        {"user":"Ahmed Mohammed","rating":5,"text":"One of the most profound books I have ever read. Frankl's wisdom is eternal.","date":"2024-12-10"},
        {"user":"Dr. Admin","rating":5,"text":"Required reading for every human being. Short but immeasurably powerful.","date":"2024-11-02"},
    ],
    "Clean Code": [
        {"user":"Sara Hassan","rating":5,"text":"Every developer should read this before writing a single line of production code.","date":"2024-10-18"},
        {"user":"Dr. Admin","rating":5,"text":"Changed how I write and review code. The naming conventions section alone is worth it.","date":"2024-09-25"},
    ],
    "1984": [
        {"user":"James Wilson","rating":5,"text":"More relevant today than ever. Orwell was a prophet.","date":"2024-12-05"},
        {"user":"Ahmed Mohammed","rating":5,"text":"Terrifying and beautiful simultaneously. One of the greatest novels ever written.","date":"2024-11-08"},
    ],
}

GENRES      = ["Fiction","Fantasy","Science","History","Biography","Technology",
               "Self-Help","Philosophy","Mystery","Children","Romance","Health","Art","Sports"]
AVATARS     = ["👨‍🎓","👩‍🎓","👨‍💼","👩‍💼","👨‍🔬","👩‍🔬","👨‍🏫","👩‍🏫","🧑‍💻","👩‍💻","👨‍🎨","👩‍🎨"]
LANGS       = {"🇺🇸 English":"en","🇪🇹 Amharic":"am","🇫🇷 French":"fr","🇩🇪 German":"de","🇸🇦 Arabic":"ar","🇧🇷 Portuguese":"pt"}
LANG_LABELS = {"en":"Welcome","am":"እንኳን ደህና መጡ","fr":"Bienvenue","de":"Willkommen","ar":"أهلاً","pt":"Bem-vindo"}
